<?xml version="1.0"?>
<package format="3">
  <name>trac_ik_python</name>
  <version>0.1.0</version>
  <description>kinematics for python based on kdl and trac_ik library</description>

  <maintainer email="santechselva@gmail.com">Santosh Balaji Selvaraj</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>pybind11_vendor</depend>
  <depend>pybind11</depend>
  <depend>trac_ik_lib</depend>
  <depend>orocos_kdl</depend>
  <depend>kdl_parser</depend>
  <depend>eigen</depend>

  <!-- Runtime for the sample node -->
  <exec_depend>rclpy</exec_depend>

  <!-- Python (for site-packages install path) -->
  <build_depend>python3-dev</build_depend>
  <exec_depend>python3</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
